before_script:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS travis_popdb;'
    - composer self-update
    - composer install
language: php
php:
    - 5.4
    - 5.5
script:
    - ./vendor/bin/phpunit
notifications:
    email: false
