before_script:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS travis_popdb;'
    - psql -c 'create database travis_popdb;' -U postgres
    - composer self-update
    - composer install
language: php
php:
    - 5.4
    - 5.5
    - 5.6
script:
    - ./vendor/bin/phpunit
notifications:
    email: false
