before_script:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS travis_popdb;'
    - psql -c 'create database travis_popdb;' -U postgres
    - composer self-update
    - composer install
language: php
branches:
  only:
  - master
php:
    - 5.6
    - 7.0
script:
    - ./vendor/bin/phpunit
notifications:
    email: false
